apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: blue-deployment-hpa
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: blue-target
 minReplicas: 2
 maxReplicas: 100
 targetCPUUtilizationPercentage: 15
