apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-with-node-preferred-affinity
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
             matchExpressions:
             - key: server
               operator: In
               values:
                - fast
                - slow
