apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-affinity-antiaffinity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: web
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
             matchExpressions:
             - key: run
               operator: In
               values:
                - nginx
            topologyKey: "kubernetes.io/hostname"
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
               matchExpressions:
               - key: env
                 operator: In
                 values:
                  - Staging
              topologyKey: "kubernetes.io/hostname"
