apiVersion: batch/v1
kind: Job
metadata:
  name: eks-iam-test-s3-ro
spec:
  template:
    metadata:
      labels:
        app: eks-iam-test-s3-ro
    spec:
      serviceAccountName: s3-readonly
      containers:
      - name: eks-iam-test-ro
        image: amazon/aws-cli:latest
        args: ["s3", "ls"]
      restartPolicy: Never
