apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
    name: aws-secrets
spec:
    provider: aws
    parameters:
        objects: |
            - objectName: "/Prod/Username"
              objectType: "ssmparameter"
            - objectName: "/Prod/Password"
              objectType: "ssmparameter"
