apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: new-secret
spec:
  provider: aws
  secretObjects:
    - secretName: mysecret
      type: Opaque
      data:
        - objectName: username
          key: myusername
        - objectName: password
          key: mypassword
  parameters:
      objects: |
        - objectName: "/Prod/Username"
          objectType: "ssmparameter"
          objectAlias: username
        - objectName: "/Prod/Password"
          objectType: "ssmparameter"
          objectAlias: password
