kind: Pod
apiVersion: v1
metadata:
 name: nginx-secrets
spec:
 containers:
 - image: nginx
   name: nginx
   env:
       - name: DB_USERNAME_01
         valueFrom:
           secretKeyRef:
              name: mysecret
              key: myusername
       - name: DB_PASSWORD_01
         valueFrom:
           secretKeyRef:
              name: mysecret
              key: mypassword
   volumeMounts:
   - name: aws-secrets
     mountPath: "/mnt/secrets-store"
     readOnly: true
 serviceAccountName: nginx-sa
 volumes:
   - name: aws-secrets
     csi:
       driver: secrets-store.csi.k8s.io
       readOnly: true
       volumeAttributes:
         secretProviderClass: "new-secret"
