apiVersion: batch/v1
kind: CronJob
metadata:
  name: scale-down-job
spec:
  schedule: "* * * * *"  
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure 
          containers:
          - name: kubectl
            image: bitnami/kubectl:1.22
            imagePullPolicy: IfNotPresent
            args: 
              - scale
              - deployment
              - -l
              - service=blue-target
              - --replicas=0 
          serviceAccountName: cicd 
