apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-target
spec:
  replicas: 2
  selector:
    matchLabels:
      service: blue-target
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        service: blue-target
    spec:
      containers:
      - name: blue
        image: 707015264015.dkr.ecr.us-west-2.amazonaws.com/blue:blue-v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
         limits:
           cpu: 500m
         requests:
           cpu: 200m

