apiVersion: apps/v1
kind: Deployment
metadata:
  name:  deploy-with-no-execute-taint
  labels:
    app: deploy-with-no-execute-taint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-with-no-execute-taint
  template:
    metadata:
      labels:
        app: deploy-with-no-execute-taint
    spec:
      containers:
      - name: deploy-with-no-execute-taint
        image: k8s.gcr.io/hpa-example
        ports:
        - containerPort: 80
      tolerations:
      - key: size
        operator: Equal
        value: large
        effect: NoExecute
        tolerationSeconds: 60
