---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-cluster
  region: us-west-2
  version: '1.21'
  #version: auto
iam:
  withOIDC: true
vpc:
  cidr: 172.16.0.0/16
cloudWatch:
  clusterLogging:
    enableTypes: ["authenticator"]
managedNodeGroups:
  - name: ng-new
    instanceType: t3.small
    spot: true
    minSize: 0
    desiredCapacity: 1
    maxSize: 5
    volumeSize: 30
    ssh:
      allow: true
      publicKeyPath: Devops
    labels: {role: worker}
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
        imageBuilder: true
        autoScaler: true
        ebs: true
        efs: true
        cloudWatch: true
