kind: Pod
apiVersion: v1
metadata:
  name: custompod
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
      - mountPath: "/var/www/html"
        name: external
  volumes:
    - name: external 
      persistentVolumeClaim:
        claimName: slow
