apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        env:
          - name: POD_NAME
            valueFrom:
             fieldRef:
               fieldPath: metadata.name
          - name: HOST_NAME
            valueFrom:
             fieldRef:
               fieldPath: spec.nodeName
          - name: NS_NAME
            valueFrom:
              fieldRef:
               fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
               fieldPath: status.podIP
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
