apiVersion: apps/v1 
kind: "DaemonSet" 
metadata: 
  labels: 
    app: nginx 
    ssd: "true" 
  name: nginx-ds
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      ssd: "ds" 
  template: 
    metadata: 
      labels: 
        app: nginx 
        ssd: "ds" 
    spec: 
      containers: 
        - name: nginx 
          image: nginx:1.23
